### ISSUE TITLE
InvalidCastException

### ISSUE THREAD

**Issue by GOMTHAA** [AhmerAli1813/Online_Help_Desk#3]
After entering admin as both user name and password in database,when i try to login it shows "InvalidCastException: Unable to cast object of type 'System.Int32' to type 'System.String'."

**Comment by AhmerAli1813** [comment]
That issue comes when you try to assign string value in int

**Comment by AhmerAli1813** [comment]
update Script Add new form
JSIL_VSP_CRS_Form
JSIL_VSP_Covid19_Form
JSIL_VSP_W9_Form

**Comment by GOMTHAA** [comment]
But im unable to change that can u help me with that?

**Comment by AhmerAli1813** [comment]
Yeah, I can.

**Comment by GOMTHAA** [comment]
Its working sir.....thank you

**Comment by AhmerAli1813** [comment]
You're welcome!

**Comment by GOMTHAA** [comment]
SmtpException: The SMTP server requires a secure connection or the client was not authenticated. The server response was: 5.7.57 Client not authenticated to send mail. Error: 535 5.7.139 Authentication unsuccessful, basic authentication is disabled. [MA0PR01CA0068.INDPRD01.PROD.OUTLOOK.COM 2024-10-15T16:18:27.237Z 08DCECCED383AD48]



When i try to login

**Comment by AhmerAli1813** [comment]
Create a new email on outlook
enter username password then you try it working.
